version: 2
updates:
  - package-ecosystem:
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    groups:
      all-dependencies:
        patterns:
          - "*"
